// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://refqlayhvpwliquwchah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlZnFsYXlodnB3bGlxdXdjaGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MTAwMTIsImV4cCI6MjA3ODk4NjAxMn0.IzTXbj6m-990fREBjfIamiZyLJ9C_r3fNWHKEFcJqv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});