// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbkmyskoochtyomoprfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRia215c2tvb2NodHlvbW9wcmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTAxNDAsImV4cCI6MjA3NDYyNjE0MH0.I5X1_i0qLhsycueXA0okw9vFPoMnEXI8nsREfzSDDsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});